FROM debian:11
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install python3-pip
RUN pip install fastapi uvicorn
WORKDIR /srv
COPY app1.py app1.py
CMD uvicorn app1:app --reload --host 0.0.0.0